typography_spectrum: 0.8086511045694351
color:
  brandStrength: 0.8143115965649486
  lightness: 0.061146259075030684
  saturation: 0.6137142335064709
  rhythmicContrast: 0.18101141951046884
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
layout_spectrum: 0.15866229380480945
name: Baby Signs
navigation:
  - name: Interst
    url: 'https://www.babygebaren.nl/'
    type: external
title: Baby Signs
description: Use it to communicate
